name: bitnet
description: You'll own everything and be happy!
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter


  intl: any
  flutter_localized_locales: ^2.0.5
  get:
  animate_do: ^3.1.2
  web_socket_channel: ^2.4.0
  number_paginator: ^0.4.0
  vector_math: ^2.1.0
  #android_id: ^0.3.6

  flutter_sound: ^9.2.13
  flutter_inappwebview: ^5.7.2+3
  youtube_player_flutter: ^8.1.2
  #either_dart: ^1.0.0
  like_button: ^2.0.5
  #marquee: ^2.2.3
  #flutter_layout_grid: ^2.0.5
  #another_flushbar: ^1.12.30
  blockchain_utils: ^2.1.2

  adaptive_dialog: ^1.9.0-no-macos.2
  #animations: ^2.0.7
  #badges: ^2.0.3
  #blurhash_dart: ^1.2.1
  #flutter_blurhash: ^0.8.2
  #callkeep: ^0.3.3
  #chewie: ^1.3.6
  collection: ^1.16.0
  connectivity_plus:  any
  #desktop_drop: ^0.4.0
  #desktop_lifecycle: ^0.1.0
  #desktop_notifications: ^0.6.3
  device_info_plus: ^10.1.2
  dynamic_color: ^1.6.0
  #emoji_picker_flutter: ^1.5.1
  #emoji_proposal: ^0.0.1
  #emojis: ^0.9.9
  #flutter_app_badger: ^1.5.0
  flutter_app_lock: ^3.0.0
  flutter_cache_manager: ^3.3.0
  #flutter_foreground_task: ^3.10.0
  flutter_highlighter: ^0.1.1
  #flutter_html: ^3.0.0-beta.2
  #flutter_html_table: ^3.0.0-beta.2
  #flutter_linkify: ^6.0.0
  #flutter_local_notifications: ^12.0.2
  #flutter_map: ^3.1.0
  #flutter_math_fork: ^0.7.2
  flutter_ringtone_player: ^3.1.1
  #flutter_typeahead: ^4.3.2
  #flutter_web_auth_2: ^2.1.1
  #flutter_webrtc: ^0.9.30+hotfix.2
  future_loading_dialog: ^0.2.3
  #handy_window: ^0.1.9
  #hive: ^2.2.3
  hive_flutter: ^1.1.0
  #just_audio_mpv: ^0.1.6
  #latlong2: ^0.8.1
  #linkify: ^5.0.0
  #matrix: ^0.20.1
  #matrix_homeserver_recommendations: ^0.3.0
  #native_imaging: ^0.1.0
  package_info_plus: ^4.0.0
  punycode: ^1.0.0
  #qr_flutter: ^4.0.0
  #receive_sharing_intent: ^1.4.5
  #record: ^4.4.4
  #scroll_to_index: ^3.0.1
  share_plus: ^7.2.1
  #slugify: ^2.0.0
  #  scrollable_positioned_list: ^0.3.8
  #swipe_to_action: ^0.2.0
  flutter_card_swiper: ^7.0.1
  #tor_detector_web: ^1.1.0
  uni_links: ^0.5.1
  #unifiedpush: ^4.0.3
  universal_html: ^2.2.3
  url_launcher: ^6.0.20
  vibration: ^1.7.4-nullsafety.0
  #video_compress: ^3.1.1
  #video_player: ^2.2.18
  #webrtc_interface: ^1.0.13
  #wakelock: ^0.6.2
#  persona_flutter: ^3.2.8

  app_links: ^6.3.1
#  persona_flutter: ^3.2.8
  animated_text_kit: ^4.2.2
  animated_flip_counter: ^0.2.6
  flutter_secure_storage: ^5.0.2
  mockito: ^5.3.2
  #flash: ^2.0.5+1
  local_auth: ^2.1.6
  flutter_multi_formatter: ^2.11.2
  bolt11_decoder: ^1.0.2
  #rive: ^0.10.0
  mobile_scanner: ^5.1.1
  #page_transition: ^2.0.9
  buttons_tabbar: ^1.3.6
  pin_code_fields: ^8.0.1
  #floating_bottom_navigation_bar: ^1.5.2
  #pointycastle: ^3.3.0
  #asn1lib: ^1.0.0
  #jose: ^0.3.0
  bip39_mnemonic: ^3.0.6
  #line_awesome_flutter: ^2.0.0
  #community_material_icon: ^5.9.55
  #camera: ^0.10.3+2
  flutter_screenutil: ^5.9.0
  animated_theme_switcher: ^2.0.6
  pretty_qr_code: ^3.1.0
  cloud_firestore: ^4.3.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.0.9
  cloud_functions: ^4.0.6
  #firebase_dynamic_links: ^5.4.8
  #injectable: ^1.5.3
  firebase_auth: ^4.2.3
  firebase_app_check: ^0.2.1+8
  uuid: ^3.0.7
  #google_sign_in: ^5.4.0
  #animator: ^3.3.0
  avatar_glow: ^2.0.2
  flutter_svg: ^2.0.6
  dio: ^5.7.0
  #json_annotation: ^4.0.0
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.15
  just_audio: ^0.9.20
  #just_waveform: ^0.0.3
  #get_it: ^7.2.0

  equatable: ^2.0.3
  #model_viewer_plus: ^1.3.0
  timeago: ^3.1.0
  permission_handler: ^10.1.0
  #random_string: ^2.3.1
  #curved_navigation_bar: ^1.0.3
  #bubble_tab_indicator: ^0.1.6
  syncfusion_flutter_charts: ^20.2.36
  syncfusion_flutter_gauges: ^20.2.36
  #fl_chart: ^0.55.2
  smooth_page_indicator: ^1.0.0+2
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.1.0
  #flutter_colorpicker: ^1.0.3 needs replacement with this flex_color_picker: ^3.5.0
  flutter_toggle_tab: ^1.2.0
  switcher: ^1.0.0
  #liquid_pull_to_refresh: ^3.0.1
  provider: ^6.0.2
  cached_network_image: ^3.3.1
  http: ^0.13.3
  file_picker: ^5.2.1
  image_picker: ^0.8.4+4
  path_provider: ^2.0.5
  google_fonts: ^4.0.4
  lottie: ^1.4.3
  image: ^4.0.17
  #extended_image: ^6.2.1
  font_awesome_flutter: ^10.2.1
  #floating_frosted_bottom_bar: ^0.0.1
  seo: ^0.0.6
  popover: ^0.2.8+2
  sliding_up_panel: ^2.0.0+1
  intl_generator: ^0.4.1
  build_runner: ^2.4.8
  gauge_indicator: ^0.4.3
  nfc_manager: ^3.4.0
  go_router: ^13.2.2
  flutter_stripe: ^11.0.0
  dart_lnurl: ^0.2.1
  logger: ^1.4.0
  photo_manager: ^3.2.2
  photo_manager_image_provider: ^2.1.1
  dio_smart_retry: ^6.0.0

  #flutter_gen: any CAUSES ISSUES TO FIND l10N
  #keyboard_shortcuts: any
  rxdart: any
  flutter_localizations:
    sdk: flutter
  country_state_city: ^0.1.6
  geolocator: ^7.7.1
  geocoding: ^3.0.0
  carousel_slider: ^4.2.1
  scrollable_positioned_list: ^0.3.8
  flutter_keyboard_size: ^1.0.1
  shake: ^2.2.0
  #internet_popup: ^1.0.8+5

  mime: any
  html: any
  flutter_native_splash: ^2.3.7
  encrypt: ^5.0.3
  crypto: ^3.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  intl_utils: ^2.4.0
  msix: ^3.6.2
  translations_cleaner: ^0.0.5
  flutter_gen_runner: ^5.4.0
  dependency_validator: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/logo.png"
  image_path_ios: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter_native_splash:
  image: assets/splash.png
  color: "#FFFFFF"
  web: true
flutter_lints: ^2.0.0

msix_config:
  display_name: bitnet
  publisher_display_name: bitnet
  publisher: CN=bitnet, O=Head of bad integration tests, L=Matrix, S=Internet, C=EU
  identity_name: net.bit.bitnet
  logo_path: assets/logo.png
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: https
  app_uri_handler_hosts: bitnet.im, matrix.to
  execution_alias: bitnet
  sign_msix: false
  install_certificate: false

dependency_overrides:
  analyzer: ^6.0.0
  flutter_secure_storage_windows:
    git:
      url: https://gitlab.com/TheOneWithTheBraid/flutter_secure_storage_windows.git
      ref: main
  flutter_webrtc:
    git: https://github.com/krille-chan/flutter-webrtc.git
  geolocator_android:
    hosted:
      name: geolocator_android
      url: https://hanntech-gmbh.gitlab.io/free2pass/flutter-geolocator-floss
  keyboard_shortcuts:
    git:
      url: https://github.com/TheOneWithTheBraid/keyboard_shortcuts.git
      ref: null-safety
  wakelock_windows:
    git:
      url: https://github.com/chandrabezzo/wakelock.git
      ref: main
      path: wakelock_windows
  flutter_screenutil:
    git:
      url: https://github.com/izako666/flutter_screenutil
      ref: master
#  persona_flutter:
#    git:
#      url: https://github.com/weltitob/persona_flutter.git
#      ref: master

flutter_intl:
  enabled: true
  arb_dir: lib/intl  # Updated to reflect the renamed directory
  template_arbs: lib/intl/intl_en.arb  # Ensure this matches the template ARB file
  output_dir: lib/generated  # Directory for generated Dart localization files

flutter:
  fonts:
    - family: SatoshiSymbol
      fonts:
        - asset: assets/fonts/Satoshi Symbol.ttf

  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/tokens/
    - assets/images/
    - assets/marketplace/
    - assets/lottiefiles/
    - assets/textfiles/
    - assets/keys/
