import 'package:flutter/material.dart';

const Map<String, String> supportedCurrencies = {
  "BTC": "Bitcoin",
  "USD": "United States Dollar",
  "AED": "United Arab Emirates Dirham",
  "ARS": "Argentine Peso",
  "AUD": "Australian Dollar",
  "BDT": "Bangladeshi Taka",
  "BHD": "Bahraini Dinar",
  "BMD": "Bermudian Dollar",
  "BRL": "Brazilian Real",
  "CAD": "Canadian Dollar",
  "CHF": "Swiss Franc",
  "CLP": "Chilean Peso",
  "CNY": "Chinese Yuan",
  "CZK": "Czech Koruna",
  "DKK": "Danish Krone",
  "EUR": "Euro",
  "GBP": "British Pound Sterling",
  "GEL": "Georgian Lari",
  "HKD": "Hong Kong Dollar",
  "HUF": "Hungarian Forint",
  "IDR": "Indonesian Rupiah",
  "ILS": "Israeli New Shekel",
  "INR": "Indian Rupee",
  "JPY": "Japanese Yen",
  "KRW": "South Korean Won",
  "KWD": "Kuwaiti Dinar",
  "LKR": "Sri Lankan Rupee",
  "MMK": "Myanmar Kyat",
  "MXN": "Mexican Peso",
  "MYR": "Malaysian Ringgit",
  "NGN": "Nigerian Naira",
  "NOK": "Norwegian Krone",
  "NZD": "New Zealand Dollar",
  "PHP": "Philippine Peso",
  "PKR": "Pakistani Rupee",
  "PLN": "Polish Złoty",
  "RUB": "Russian Ruble",
  "SAR": "Saudi Riyal",
  "SEK": "Swedish Krona",
  "SGD": "Singapore Dollar",
  "THB": "Thai Baht",
  "TRY": "Turkish Lira",
  "TWD": "New Taiwan Dollar",
  "UAH": "Ukrainian Hryvnia",
  "VEF": "Venezuelan Bolívar",
  "VND": "Vietnamese đồng",
  "ZAR": "South African Rand",
  "XDR": "Special Drawing Rights",
  "XAG": "Silver Ounce",
  "XAU": "Gold Ounce"
};
